// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ8IOjU1XfdWfeZ5ly0ACsCXWl70MStgs',
    appId: '1:654641458495:web:a4ce795cf89a67c4ad778a',
    messagingSenderId: '654641458495',
    projectId: 'firecloud-v1',
    authDomain: 'firecloud-v1.firebaseapp.com',
    storageBucket: 'firecloud-v1.appspot.com',
    measurementId: 'G-E6KHG8581W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx3YsNjhRZmEEEA7xBDvl7Y8vDJZhCptk',
    appId: '1:654641458495:android:2296817afec87962ad778a',
    messagingSenderId: '654641458495',
    projectId: 'firecloud-v1',
    storageBucket: 'firecloud-v1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVgOPbVR46w6_Eo1wpjikIwFNnvKbsm1M',
    appId: '1:654641458495:ios:5c68efb24798a8acad778a',
    messagingSenderId: '654641458495',
    projectId: 'firecloud-v1',
    storageBucket: 'firecloud-v1.appspot.com',
    iosBundleId: 'dev.nagarajmh.cloud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVgOPbVR46w6_Eo1wpjikIwFNnvKbsm1M',
    appId: '1:654641458495:ios:5c68efb24798a8acad778a',
    messagingSenderId: '654641458495',
    projectId: 'firecloud-v1',
    storageBucket: 'firecloud-v1.appspot.com',
    iosBundleId: 'dev.nagarajmh.cloud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZ8IOjU1XfdWfeZ5ly0ACsCXWl70MStgs',
    appId: '1:654641458495:web:37aa1dd2f6c8ffd2ad778a',
    messagingSenderId: '654641458495',
    projectId: 'firecloud-v1',
    authDomain: 'firecloud-v1.firebaseapp.com',
    storageBucket: 'firecloud-v1.appspot.com',
    measurementId: 'G-8SJXJ7GW0P',
  );

}